// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWl8YRRjPu5BjOnmOjijrpc2qi2QFDSY',
    appId: '1:448069139837:web:ddad334e4cdb062d792014',
    messagingSenderId: '448069139837',
    projectId: 'gicc-f1622',
    authDomain: 'gicc-f1622.firebaseapp.com',
    storageBucket: 'gicc-f1622.appspot.com',
    measurementId: 'G-47PQWPXJMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJgTxMgk2o6tNSFo02blQlOTxS6hW1ZWI',
    appId: '1:448069139837:android:868fe857e93ff9a7792014',
    messagingSenderId: '448069139837',
    projectId: 'gicc-f1622',
    storageBucket: 'gicc-f1622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJg_0Jf6x1jcg0XRAlMmYP6DdFpH2Smk',
    appId: '1:448069139837:ios:c506452c4b2c6b95792014',
    messagingSenderId: '448069139837',
    projectId: 'gicc-f1622',
    storageBucket: 'gicc-f1622.appspot.com',
    iosBundleId: 'com.example.gicc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtJg_0Jf6x1jcg0XRAlMmYP6DdFpH2Smk',
    appId: '1:448069139837:ios:d3a0c726f313a6a8792014',
    messagingSenderId: '448069139837',
    projectId: 'gicc-f1622',
    storageBucket: 'gicc-f1622.appspot.com',
    iosBundleId: 'com.example.islamicCenterPrayerTimes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWl8YRRjPu5BjOnmOjijrpc2qi2QFDSY',
    appId: '1:448069139837:web:b18fcc14073b00d4792014',
    messagingSenderId: '448069139837',
    projectId: 'gicc-f1622',
    authDomain: 'gicc-f1622.firebaseapp.com',
    storageBucket: 'gicc-f1622.appspot.com',
    measurementId: 'G-PCVMVZPBWJ',
  );

}