// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBXPTNtQuOug4bmfBfIbhdsnqLZeHhrk',
    appId: '1:247960570637:web:4d492da964e3e11143fe44',
    messagingSenderId: '247960570637',
    projectId: 'prayer-times-1c62a',
    authDomain: 'prayer-times-1c62a.firebaseapp.com',
    storageBucket: 'prayer-times-1c62a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqQmipkmIxe19uiN9eiCDEmNhAyicsk8',
    appId: '1:247960570637:android:39a1b692395f592043fe44',
    messagingSenderId: '247960570637',
    projectId: 'prayer-times-1c62a',
    storageBucket: 'prayer-times-1c62a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcg3DK9y-VQxpkY8Ebk5bVq5UpJ5lrO0',
    appId: '1:247960570637:ios:7b7314351660660b43fe44',
    messagingSenderId: '247960570637',
    projectId: 'prayer-times-1c62a',
    storageBucket: 'prayer-times-1c62a.appspot.com',
    iosBundleId: 'com.example.islamicCenterPrayerTimes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkcg3DK9y-VQxpkY8Ebk5bVq5UpJ5lrO0',
    appId: '1:247960570637:ios:985eecaa53e9bddf43fe44',
    messagingSenderId: '247960570637',
    projectId: 'prayer-times-1c62a',
    storageBucket: 'prayer-times-1c62a.appspot.com',
    iosBundleId: 'com.example.islamicCenterPrayerTimes.RunnerTests',
  );
}
